@startuml
!include puml-theme-pfe.puml

start
:Affectation des jurys;
repeat
  :Vérification des conflits;
backward:Correction manuelle;
:Mise à jour du planning;
repeat while (Conflits détectés ?) is (Oui)
-> Non;
:Validation du planning final;
stop
@enduml
