@startuml
!include puml-theme-pfe.puml

actor "Coordinateur" as Coord
boundary "Tableau de bord" as Front
control "Controller" as Controller
entity "Planning Service" as Service
entity "Notification Service" as Notify
database "Base de données" as DB

Coord -> Front : Clique sur "Valider planning"
Front -> Controller : POST /api/planning/validate-global-session (sessionGlobaleId)
activate Controller

Controller -> Service : validerSessionGlobale(id)
activate Service

Service -> DB : Vérifier conformité de la session globale
activate DB
DB --> Service : OK
deactivate DB

Service -> DB : Mise à jour statuts (PLANIFIEE -> CONVOQUEE)
activate DB
DB --> Service : OK
deactivate DB

Service -> DB : Clôturer modifications
activate DB
DB --> Service : OK
deactivate DB

Service -> Notify : envoyerNotificationsMassives(sessionGlobaleId)
activate Notify
Notify -> DB : Récupérer emails (Étudiants, Jurys)
activate DB
DB --> Notify : Liste emails
deactivate DB
Notify -> Notify : Envoi e-mails 
Notify --> Service : Notifications envoyées
deactivate Notify

Service --> Controller : Planning de la session globale validé
deactivate Service

Controller --> Front : 200 OK
deactivate Controller

Front --> Coord : Afficher succès et verrouillage de la session globale

@enduml
