@startuml
!include puml-theme-pfe.puml
left to right direction

actor "Administrateur" as Admin

rectangle "Module Administration" {
    usecase "Gérer comptes utilisateurs" as UC1
    usecase "Gérer salles" as UC2
    usecase "Gérer les sessions globales" as UC3
    usecase "Gérer les  paramètres du système" as UC4
}

Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC4
@enduml
