@startuml
!include puml-theme-pfe.puml
left to right direction

actor "Coordinateur" as Coord

rectangle "Module Coordination" {
    usecase "Gérer les projets" as UC11
    usecase "Planifier soutenances" as UC4
    usecase "Assigner jurys" as UC1
    usecase "Valider planning" as UC3
    usecase "Générer convocations" as UC5
    usecase "Générer planning général" as UC6
    usecase "Consulter rapports" as UC2

    usecase "Consulter planning" as UC9
    usecase "Vérifier conflits" as Check
    usecase "Rechercher / Filtrer" as UC10


    UC1 ..> Check : <<include>>
    UC3 ..> Check : <<include>>
    UC6 ..> UC9 : <<include>>
    UC10 ..> UC9 : <<extend>>
}

Coord --> UC11
Coord --> UC4
Coord --> UC1
Coord --> UC3
Coord --> UC5
Coord --> UC6
Coord --> UC2

@enduml
