@startuml
!include puml-theme-pfe.puml
left to right direction

actor "Utilisateur" as User
actor "Administrateur" as Admin
actor "Coordinateur" as Coord
actor "Enseignant / Membre de jury" as Jury
actor "Étudiant" as Student

usecase "S'authentifier" as auth

Admin --|> User
Coord --|> User
Jury --|> User
Student --|> User

User -> auth
@enduml
