@startuml
!include puml-theme-pfe.puml
left to right direction

together {
    actor "Administrateur" as Admin
    actor "Coordinateur" as Coord
    actor "Enseignant / Membre de jury" as Jury
    actor "Étudiant" as Student

    actor "Utilisateur" as User
}

rectangle "Authentification" {
    usecase "Se connecter" as Login
    usecase "Activer son compte" as Activate
    usecase "Réinitialiser mot de passe" as ResetPwd
    usecase "Demander réinitialisation" as ForgotPwd
    usecase "Se déconnecter" as Logout
}

rectangle "Profil et Préférences" {
    usecase "Consulter son profil" as Profile
    usecase "Gérer ses notifications" as Notif
}

Admin --|> User
Coord --|> User
Jury --|> User
Student --|> User

User ---> Login
User ---> Activate
User ---> ResetPwd
User ---> ForgotPwd
User ---> Logout
User ---> Profile
User ---> Notif

ResetPwd ..> ForgotPwd : <<include>>
@enduml
