@startuml
!include puml-theme-pfe.puml
left to right direction

actor "Enseignant / Membre de jury" as Jury

rectangle "Module Enseignant" {
    usecase "Consulter le planning" as Schedule
    usecase "Déclarer des\nindisponibilités" as Unavail
    usecase "Saisir les évaluations" as EvalInput
    usecase "Soumettre les\évaluations" as EvalSubmit
    usecase "Consulter l'historique\ndes évaluations" as EvalHistory
}

EvalSubmit ..> EvalInput : <<include>>
EvalHistory ..> EvalInput : <<extend>>

Jury --> Schedule
Jury --> Unavail
Jury --> EvalInput
Jury --> EvalSubmit
Jury --> EvalHistory
@enduml
