@startuml
!include puml-theme-pfe.puml
left to right direction

actor "Enseignant / Membre de jury" as Jury

rectangle "Module Jury" {
    usecase "Consulter planning" as UC1
    usecase "Consulter convocation" as UC2
    usecase "Déclarer indisponibilité" as UC3
    usecase "Saisir évaluation" as UC4
    usecase "Générer fiches d'évaluation" as UC5

    usecase "Consulter informations étudiant" as UC7
    usecase "Valider / modifier évaluation" as UC6

    UC6 -[hidden]up- UC5
    UC6 -[hidden]left- UC4

    UC6 ..> UC4 : <<extend>>
    UC4 ..> UC7 : <<include>>
}

Jury --> UC1
Jury --> UC2
Jury --> UC3
Jury --> UC5
Jury --> UC4
@enduml
