@startuml
!include puml-theme-pfe.puml
left to right direction

actor "Étudiant" as Student

rectangle "Module Étudiant" {
    usecase "Télécharger convocation" as UC1
    usecase "Consulter infos de soutenance" as UC2
    usecase "Consulter résultats" as UC3
}

Student --> UC1
Student --> UC3

UC1 ..> UC2 : <<include>>
@enduml