@startuml
!include puml-theme-pfe.puml
left to right direction

actor "Étudiant" as Student

rectangle "Module Étudiant" {
    usecase "Consulter le tableau\nde bord" as Dashboard
    usecase "Créer un groupe" as CreateGroup
    usecase "Rejoindre un groupe" as JoinGroup
    usecase "Consulter son groupe" as ViewGroup
    usecase "Consulter les détails\nde la soutenance" as DefenseDetails
    usecase "Télécharger\nla convocation" as DownloadConv
    usecase "Téléverser\ndes documents" as UploadDocs
    usecase "Consulter le résultat\nde la soutenance" as Result
}

DownloadConv ..> DefenseDetails : <<include>>
Result ..> DefenseDetails : <<extend>>

Student --> Dashboard
Student --> CreateGroup
Student --> JoinGroup
Student --> ViewGroup
Student --> DownloadConv
Student --> UploadDocs
Student --> Result
@enduml
